import Head from 'next/head'
import Link from 'next/link'
import React from 'react'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { MyFormElement } from '../lib/utils';

const inter = Inter({ subsets: ['latin'] })


export default function Home() {
  // const data = getStockInfo('')

  return (
    <>
      <Head>
        <title>Novig Stock Profile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Welcome to Novig&apos;s Stock Profile API
          </p> 
          <Link target='_blank' href='https://financialmodelingprep.com/developer/docs/'>Data provided by Financial Modeling Prep</Link>
        </div>

        <div className={styles.content}>
          <form className={styles.card} onSubmit={handleFormSubmit}>
            <label htmlFor="ticker">Ticker </label>
            <input
              type="text"
              id="ticker"
              name="ticker"
              placeholder='e.g. AAPL'
              pattern='[a-zA-Z]{1,5}'
              required
            />
            <button type="submit">Submit</button>
          </form>

          <div className={styles.code}>
            {/* <p>{data}</p> */}
          </div>
        </div>
      </main>
    </>
  )
}

const handleFormSubmit = async (e: React.FormEvent<MyFormElement>) => {
  e.preventDefault();
  const ticker = e.currentTarget.elements.ticker.value
  // return
  const data = await getStockInfo(ticker)
  return data
}

const getStockInfo = async (ticker: string) => {
  // API endpoint for GET request
  const endpoint = '/stocks/'+ticker
  const res = await fetch(endpoint)
  const json = await res.json()
  return json
}