import Head from 'next/head'
import Link from 'next/link'
import React, { useCallback, useState } from 'react'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { MyFormElement } from '../lib/utils';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [ticker, setTicker] = useState("");
  const [data, setData] = useState("");
  
  const getStockInfo = useCallback(async () => {
    // API endpoint for GET request
    const endpoint = `/stocks/${ticker}`
    const res = await fetch(endpoint)
    const json = await res.json()
    return json
  }, [ticker]);

  const handleFormSubmit = useCallback(async () => {
    const data = await getStockInfo()
    setData(data);
  }, [getStockInfo]);


  return (
    <>
      <Head>
        <title>Novig Stock Profile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Welcome to Novig&apos;s Stock Profile API
          </p> 
          <Link target='_blank' href='https://financialmodelingprep.com/developer/docs/'>Data provided by Financial Modeling Prep</Link>
        </div>

        <div className={styles.content}>
          <div className={styles.card}>
            <label htmlFor="ticker">Ticker </label>
            <input
              type="text"
              id="ticker"
              name="ticker"
              placeholder='e.g. AAPL'
              pattern='[a-zA-Z]{1,5}'
              required
              onChange={(e) => setTicker(e.target.value)}
            />
            <button onClick={handleFormSubmit}>Submit</button>
          </div>

          <div className={styles.code}>
            <pre>{JSON.stringify(data, null, 2)}</pre>
          </div>
        </div>
      </main>
    </>
  )
}
